"""Audited CREOSON allowlist: request schemas, safe wire defaults and readback rules.

Only entries in this table are exposed. No arbitrary command/function passthrough.
API field names are based on published CREOSON/Creopyson interfaces; see SOURCES.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from .core import Error, number

SOURCES = {
    "file": ("Zepmanbc/creopyson", "creopyson/file.py", "228f71eb3fcb3a34764c4dc145686b79fffdf9b8"),
    "parameter": ("Zepmanbc/creopyson", "creopyson/parameter.py", "cba1c8decb1c851bcea14f224b601baef4f93023"),
    "dimension": ("Zepmanbc/creopyson", "creopyson/dimension.py", "91e4c616f23edeab574bb270510be245137c9009"),
    "feature": ("Zepmanbc/creopyson", "creopyson/feature.py", "fb2d7892d0c192bf68b700512e48ec886e3ca6e3"),
    "interface": ("Zepmanbc/creopyson", "creopyson/interface.py", "997640a896b69c0482dc0a3a1ef285a747d353c1"),
    "view": ("Zepmanbc/creopyson", "creopyson/view.py", "ebdae69b795ef042f67da9f601781fa9b2b33e20"),
    "drawing": ("Zepmanbc/creopyson", "creopyson/drawing.py", "e0ad14a5f1c5da6b261efc16efb8181432c4bf68"),
    "bom": ("Zepmanbc/creopyson", "creopyson/bom.py", "611209b7f6695bdce8f3d08bdaa4096d3bbdef54"),
    "creo": ("Zepmanbc/creopyson", "creopyson/creo.py", "678c83bdcafd67c5a838959c9080a20989c29d80"),
    "connection": ("Zepmanbc/creopyson", "creopyson/connection.py", "cc1bd8ebf59f3139d1906fda9e159e16bd78c109"),
}

# Command groups cited against CREOSON's own released specification rather than a
# client re-implementation of it. Provenance is per function, not per group: the blob
# identities come from creoson_spec_ids, generated by scripts/gen_creoson_interface.py.
SPEC_SOURCED = {"server", "geometry", "layer", "note", "familytable"}
SPEC_REPOSITORY_PREFIX = "creoson-server/"


def obj(properties: dict, required: tuple | None = None) -> dict:
    return {"type": "object", "properties": properties,
            "required": list(properties if required is None else required), "additionalProperties": False}


def text(*, enum: tuple = (), pattern: str | None = None, maximum: int = 256) -> dict:
    result: dict = {"type": "string", "minLength": 1, "maxLength": maximum}
    if enum:
        result["enum"] = list(enum)
    if pattern:
        result["pattern"] = pattern
    return result


NAME = text(pattern=r"^[A-Za-z_][A-Za-z0-9_]{0,79}$")
MODEL = text(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_-]{0,79}\.(?:prt|asm|drw)$")
PART = text(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_-]{0,79}\.prt$")
ASM = text(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_-]{0,79}\.asm$")
DRAWING = text(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_-]{0,79}\.drw$")
NUM = {"type": "number", "minimum": -1e9, "maximum": 1e9}
POS = {"type": "number", "exclusiveMinimum": 0, "maximum": 1e9}
BOOL = {"type": "boolean"}
SHEET = {"type": "integer", "minimum": 1, "maximum": 10000}
PATH = text(maximum=2048)
POINT = obj({"x": NUM, "y": NUM, "z": NUM}, ("x", "y"))
VECTOR = obj({"x": NUM, "y": NUM, "z": NUM})
LENGTH = text(enum=("mm", "cm", "m", "in", "ft"))
F = {"file": MODEL}
D = {"drawing": DRAWING}
PARAM_VALUE = {"type": ["string", "number", "boolean"], "maxLength": 4000}
CONSTRAINT = obj({"type": text(enum=("csys", "fix")), "asmref": NAME, "compref": NAME}, ("type",))


@dataclass(frozen=True)
class Operation:
    path: str
    command: str
    function: str
    description: str
    request_schema: dict
    response_fields: tuple
    example: dict
    write: bool = False
    target_keys: tuple = ("file",)
    defaults: dict = field(default_factory=dict)
    local_keys: tuple = ()
    verifier: str = "observation"
    list_key: str | None = None
    effect: str = "read"
    dangerous: bool = False
    version_required: bool = False
    interaction_risks: tuple = ()

    def source(self) -> dict:
        if self.command in SPEC_SOURCED:
            from .creoson_spec_ids import REPOSITORY, SPEC_BLOB_SHA, SPEC_SUBDIR
            key = f"{self.command}.{self.function}"
            return {"repository": REPOSITORY,
                    "path": f"{SPEC_REPOSITORY_PREFIX}{SPEC_SUBDIR}/{self.command}-{self.function}.json",
                    "git_blob_sha": SPEC_BLOB_SHA[key], "protocol_target": "CREOSON 3.0.2",
                    "source_kind": "published_release_specification", "live_verified": False}
        repo, path, sha = SOURCES[self.command]
        return {"repository": repo, "path": path, "git_blob_sha": sha,
                "protocol_target": "CREOSON 3.0.2", "source_kind": "published_source_snapshot", "live_verified": False}

    def validate(self, request: Any) -> dict:
        validate(request, self.request_schema)
        q = dict(request)
        if self.path == "parameter set":
            kind, value = q["type"], q["value"]
            matches = {"STRING": type(value) is str, "DOUBLE": number(value),
                       "INTEGER": type(value) is int and -(2**31) <= value < 2**31,
                       "BOOL": type(value) is bool}
            if not matches[kind]:
                raise Error("E_VALIDATION", "parameter value does not match its explicit type")
        if self.path == "familytable set-cell":
            kind, value = q["expected_datatype"], q["value"]
            matches = {"STRING": type(value) is str, "DOUBLE": number(value),
                       "INTEGER": type(value) is int and -(2**31) <= value < 2**31,
                       "BOOL": type(value) is bool}
            if not matches[kind]:
                raise Error("E_VALIDATION", "cell value does not match its expected declared data type")
        if self.path == "assembly assemble":
            constraints = q["constraints"]
            if len(constraints) != 1:
                raise Error("E_UNSUPPORTED", "this adapter supports exactly one coordinate-system or fixed constraint")
            c = constraints[0]
            if c["type"] == "csys":
                if set(c) != {"type", "asmref", "compref"} or "transform" in q:
                    raise Error("E_VALIDATION", "csys constraint needs explicit asmref/compref and no transform")
            elif set(c) != {"type"} or "transform" not in q:
                raise Error("E_VALIDATION", "fixed assembly needs an explicit transform and no implicit selection")
        if self.path == "drawing project-view":
            p = q["point"]
            if (p.get("x", 0) == 0) == (p.get("y", 0) == 0):
                raise Error("E_VALIDATION", "projection offset must have exactly one nonzero x or y coordinate")
        if self.path.startswith("export "):
            import re
            suffix = {"export step": r"\.(?:stp|step)$", "export iges": r"\.(?:igs|iges)$",
                      "export dxf": r"\.dxf$", "export pdf": r"\.pdf$", "export image": r"\.(?:jpg|jpeg)$"}[self.path]
            if not re.search(suffix, q["filename"], re.I) or any(x in q["filename"] for x in ("/", "\\", ":", "..", "*", "?")):
                raise Error("E_VALIDATION", "export filename must be a basename with the matching extension")
        return q

    def wire(self, request: dict) -> dict:
        return self.defaults | {k: v for k, v in request.items() if k not in self.local_keys}


def validate(value: Any, schema: dict, path: str = "request", depth: int = 0) -> None:
    """Strict input subset shared with workflow manifests; reject unknown fields."""
    import re
    if depth > 24:
        raise Error("E_VALIDATION", "request nesting limit exceeded")
    kinds = schema.get("type", [])
    kinds = [kinds] if isinstance(kinds, str) else kinds
    matches = {"object": type(value) is dict, "array": type(value) is list,
               "string": type(value) is str, "integer": type(value) is int,
               "number": number(value), "boolean": type(value) is bool, "null": value is None}
    if kinds and not any(matches[k] for k in kinds):
        raise Error("E_VALIDATION", "wrong request value type", {"path": path})
    if "enum" in schema and value not in schema["enum"]:
        raise Error("E_VALIDATION", "unsupported request value", {"path": path, "allowed": schema["enum"]})
    if isinstance(value, dict):
        props = schema.get("properties", {})
        if set(value) - set(props) or set(schema.get("required", [])) - set(value):
            raise Error("E_VALIDATION", "request has missing or unknown fields",
                        {"path": path, "unknown": sorted(set(value) - set(props)),
                         "missing": sorted(set(schema.get("required", [])) - set(value))})
        for k, v in value.items():
            validate(v, props[k], path + "." + k, depth + 1)
    elif isinstance(value, list):
        if not schema.get("minItems", 0) <= len(value) <= schema.get("maxItems", 1000):
            raise Error("E_VALIDATION", "request list size out of range", {"path": path})
        for v in value:
            validate(v, schema.get("items", {}), path + "[]", depth + 1)
    elif isinstance(value, str):
        if (not schema.get("minLength", 0) <= len(value) <= schema.get("maxLength", 4000)
                or (schema.get("pattern") and not re.fullmatch(schema["pattern"], value))
                or "\x00" in value):
            raise Error("E_VALIDATION", "invalid request string", {"path": path})
    elif number(value):
        if (("minimum" in schema and value < schema["minimum"])
                or ("maximum" in schema and value > schema["maximum"])
                or ("exclusiveMinimum" in schema and value <= schema["exclusiveMinimum"])):
            raise Error("E_VALIDATION", "request number out of range", {"path": path})


OPS: list[Operation] = []


def add(path, command, function, description, props, response, example, **kw):
    required = kw.pop("required", None)
    OPS.append(Operation(path, command, function, description, obj(props, required), tuple(response), example, **kw))


# Reads are named, bounded observations; no wildcard model targets or UI selection.
add("file list", "file", "list", "List currently loaded models", {}, ("files",), {}, target_keys=(), list_key="files")
add("file active", "file", "get_active", "Read the active model without switching windows", {}, ("file", "dirname"), {}, target_keys=())
add("file info", "file", "get_fileinfo", "Read explicit model file information", F, ("file", "dirname", "revision"), {"file": "bracket.prt"})
add("file units", "file", "get_length_units", "Read length and mass units without conversion", F, ("length_units", "mass_units"), {"file": "bracket.prt"}, verifier="units")
add("file massprops", "file", "massprops", "Read model mass properties and unit context; density validity is not assumed", F,
    ("volume", "mass", "density", "surface_area", "ctr_grav", "coord_sys_inertia", "coord_sys_inertia_tensor", "ctr_grav_inertia_tensor", "unit_context"), {"file": "bracket.prt"}, verifier="massprops")
add("file relations", "file", "relations_get", "Read relations without evaluating them in the CLI", F, ("relations",), {"file": "bracket.prt"}, list_key="relations")
add("file instances", "file", "list_instances", "List family-table instances, not create them", F, ("generic", "dirname", "files"), {"file": "bracket.prt"}, list_key="files")
add("parameter list", "parameter", "list", "Read typed model parameters", F | {"name": NAME}, ("paramlist",), {"file": "bracket.prt"}, required=("file",), defaults={"encoded": False}, list_key="paramlist")
add("dimension list", "dimension", "list_detail", "Read dimension values, types and drawing context without selecting", F | {"name": NAME}, ("dimlist",), {"file": "bracket.prt"}, required=("file",), defaults={"encoded": False, "select": False}, list_key="dimlist")
add("feature list", "feature", "list", "Read reported visible feature identities/statuses, including unnamed features", F, ("featlist",), {"file": "bracket.prt"}, defaults={"paths": True, "inc_unnamed": True}, list_key="featlist")
add("material list", "file", "list_materials", "Read materials already loaded on a part", {"file": PART}, ("materials",), {"file": "bracket.prt"}, list_key="materials")
add("material current", "file", "get_cur_material", "Read the part's assigned material", {"file": PART}, ("material",), {"file": "bracket.prt"})
add("view list", "view", "list", "List named model orientations", F, ("viewlist",), {"file": "bracket.prt"}, list_key="viewlist")
add("assembly tree", "bom", "get_paths", "Read component hierarchy; upstream omits inactive/unregenerated components", {"file": ASM}, ("file", "generic", "children", "has_simprep"), {"file": "device.asm"}, defaults={"paths": True, "get_transforms": True, "skeletons": True})
add("assembly transform", "file", "get_transform", "Read a specific component occurrence transform", {"asm": ASM, "path": {"type": "array", "items": text(pattern=r"^[0-9]{1,10}$"), "minItems": 1, "maxItems": 32}}, ("origin", "x_axis", "y_axis", "z_axis", "x_rot", "y_rot", "z_rot"), {"asm": "device.asm", "path": ["39"]}, target_keys=("asm",))

# Session-model operations. Every one goes through preview/confirm, local policy and journal.
W = {"write": True, "effect": "memory"}
add("file open", "file", "open", "Open one explicit working-copy model; never replaces an already-loaded name", F | {"dirname": PATH}, ("files", "dirname", "revision"), {"file": "bracket.prt", "dirname": "."}, defaults={"display": True, "activate": True, "new_window": False, "regen_force": False}, verifier="open", **W)
add("file display", "file", "display", "Display and activate a specific loaded model", F, (), {"file": "bracket.prt"}, defaults={"activate": True}, verifier="active", **W)
add("file regenerate", "file", "regenerate", "Regenerate once and read feature statuses; not a full design check", F, (), {"file": "bracket.prt"}, defaults={"display": False}, verifier="regenerate", version_required=True, **W)
add("file close-window", "file", "close_window", "Close only the model window; does not erase or claim to save", F, (), {"file": "bracket.prt"}, verifier="acknowledgement", effect="ui", write=True)
add("file save", "file", "save", "Save a named working-copy model with pre-save byte backup and artifact inventory", F, (), {"file": "bracket.prt"}, verifier="save", effect="disk", write=True)
add("file backup", "file", "backup", "Back up a model and dependencies into a new workspace directory", F | {"target_dir": PATH}, (), {"file": "bracket.prt", "target_dir": "backup_bracket"}, verifier="backup", effect="disk", write=True)
add("parameter set", "parameter", "set", "Set or explicitly create one typed parameter and read it back", F | {"name": NAME, "type": text(enum=("STRING", "DOUBLE", "INTEGER", "BOOL")), "value": PARAM_VALUE, "create": BOOL}, (), {"file": "bracket.prt", "name": "PART_NO", "type": "STRING", "value": "BRK-001", "create": False}, local_keys=("create",), defaults={"encoded": False}, verifier="parameter", **W)
add("dimension set", "dimension", "set", "Set an existing dimension with explicit length units and readback", F | {"name": NAME, "value": POS, "expected_length_units": LENGTH}, (), {"file": "bracket.prt", "name": "d1", "value": 45, "expected_length_units": "mm"}, local_keys=("expected_length_units",), defaults={"encoded": False}, verifier="dimension", **W)
add("feature suppress", "feature", "suppress", "Suppress exactly one named feature; never clip or include children", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "HOLE_1"}, defaults={"clip": False, "with_children": False}, verifier="suppress", version_required=True, **W)
add("feature resume", "feature", "resume", "Resume exactly one named feature", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "HOLE_1"}, defaults={"with_children": False}, verifier="resume", version_required=True, **W)
add("feature rename", "feature", "rename", "Rename one explicitly named feature and read it back", F | {"name": NAME, "new_name": NAME}, (), {"file": "bracket.prt", "name": "HOLE_1", "new_name": "MOUNT_HOLE"}, verifier="feature_name", **W)
add("material assign", "file", "set_cur_material", "Assign a material already present in a part; never assumes a density", {"file": PART, "material": NAME}, ("files",), {"file": "bracket.prt", "material": "ALUMINUM"}, verifier="material", **W)
add("view activate", "view", "activate", "Apply an existing named model orientation", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "FRONT"}, verifier="acknowledgement", effect="ui", write=True)
add("view save", "view", "save", "Save the current orientation as a new named view", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "REVIEW"}, verifier="view", **W)
add("assembly assemble", "file", "assemble", "Assemble one loaded part using explicit csys or fixed placement; never prompts", {"file": PART, "into_asm": ASM, "constraints": {"type": "array", "items": CONSTRAINT, "minItems": 1, "maxItems": 1}, "transform": obj({"origin": VECTOR, "x_rot": NUM}, ("origin",)), "expected_length_units": LENGTH}, ("files", "dirname", "revision", "featureid"), {"file": "bracket.prt", "into_asm": "device.asm", "constraints": [{"type": "csys", "asmref": "ASM_DEF_CSYS", "compref": "PRT_CSYS_DEF"}], "expected_length_units": "mm"}, required=("file", "into_asm", "constraints", "expected_length_units"), target_keys=("file", "into_asm"), defaults={"package_assembly": True, "walk_children": False, "assemble_to_root": True, "suppress": False}, local_keys=("expected_length_units",), verifier="assemble", version_required=True, **W)

# Drawing template + explicit views. Coordinates are in drawing units, never silently in mm.
add("drawing create", "drawing", "create", "Create a named drawing from a local drawing template", {"template": PATH, "model": MODEL, "drawing": DRAWING, "scale": POS}, ("drawing",), {"template": "templates/a4.drw", "model": "bracket.prt", "drawing": "bracket.drw", "scale": 1}, target_keys=("model", "drawing"), defaults={"display": True, "activate": True, "new_window": False}, verifier="drawing_create", interaction_risks=("upstream_may_open_modal_error_dialog", "client_timeout_does_not_cancel_creo"), **W)
add("drawing add-model", "drawing", "add_model", "Add a loaded model to a named drawing", D | {"model": MODEL}, (), {"drawing": "bracket.drw", "model": "bracket.prt"}, target_keys=("drawing", "model"), verifier="drawing_models", **W)
add("drawing add-sheet", "drawing", "add_sheet", "Append one sheet to a named drawing", D, (), {"drawing": "bracket.drw"}, target_keys=("drawing",), defaults={"position": 0}, verifier="drawing_sheets", **W)
add("drawing create-view", "drawing", "create_gen_view", "Create an explicit general view in drawing units", D | {"model": MODEL, "model_view": NAME, "view": NAME, "sheet": SHEET, "point": POINT, "scale": POS, "coordinate_units": text(enum=("drawing_units",))}, (), {"drawing": "bracket.drw", "model": "bracket.prt", "model_view": "FRONT", "view": "FRONT_MAIN", "sheet": 1, "point": {"x": 100, "y": 100}, "scale": 1, "coordinate_units": "drawing_units"}, target_keys=("drawing", "model"), local_keys=("coordinate_units",), defaults={"exploded": False}, verifier="drawing_views", **W)
add("drawing project-view", "drawing", "create_proj_view", "Create one aligned projected view with an explicit parent and offset", D | {"parent_view": NAME, "view": NAME, "sheet": SHEET, "point": POINT, "coordinate_units": text(enum=("drawing_units",))}, (), {"drawing": "bracket.drw", "parent_view": "FRONT_MAIN", "view": "RIGHT_PROJECTED", "sheet": 1, "point": {"x": 100, "y": 0}, "coordinate_units": "drawing_units"}, target_keys=("drawing",), local_keys=("coordinate_units",), defaults={"exploded": False}, verifier="drawing_views", **W)
add("drawing regenerate", "drawing", "regenerate", "Regenerate a named drawing; does not certify dimensions or tolerances", D, (), {"drawing": "bracket.drw"}, target_keys=("drawing",), verifier="acknowledgement", **W)

for label, kind, ext in (("step", "STEP", "step"), ("iges", "IGES", "igs"), ("dxf", "DXF", "dxf")):
    add("export " + label, "interface", "export_file", "Export " + kind + " into a new explicit file, then verify bytes and header",
        F | {"filename": NAME | {"pattern": r"^[A-Za-z0-9_][A-Za-z0-9_.-]{0,120}$"}, "dirname": PATH},
        ("filename", "dirname"), {"file": "bracket.prt", "filename": "bracket." + ext, "dirname": "exports"},
        defaults={"type": kind, **({"geom_flags": "solids"} if kind in ("STEP", "IGES") else {})},
        verifier="export", effect="disk", write=True)
add("export pdf", "interface", "export_pdf", "Export a named model/drawing to PDF with explicit all-sheet policy", F | {"filename": text(maximum=128), "dirname": PATH}, ("filename", "dirname"), {"file": "bracket.drw", "filename": "bracket.pdf", "dirname": "exports"}, defaults={"sheet_range": "all", "use_drawing_settings": True}, verifier="export", effect="disk", write=True)
add("export image", "interface", "export_image", "Export a JPEG review image; validates file bytes, not visual correctness", F | {"filename": text(maximum=128), "dirname": PATH, "dpi": {"type": "integer", "enum": [100, 200, 300, 400, 500, 600]}}, ("filename", "dirname"), {"file": "bracket.prt", "filename": "bracket.jpg", "dirname": "exports", "dpi": 200}, defaults={"type": "JPEG", "depth": 24}, verifier="export", effect="disk", write=True)

add("drawing models", "drawing", "list_models", "Read models contained in a named drawing", D, ("files",), {"drawing": "bracket.drw"}, target_keys=("drawing",), list_key="files")
add("drawing sheets", "drawing", "get_num_sheets", "Read the sheet count", D, ("num_sheets",), {"drawing": "bracket.drw"}, target_keys=("drawing",))
add("drawing views", "drawing", "list_view_details", "Read view names, sheets, positions and referenced models", D, ("views",), {"drawing": "bracket.drw"}, target_keys=("drawing",), list_key="views")
add("file roundtrip", "file", "save", "Save, close, erase only one isolated part, reopen and compare observed design data", {"file": PART},
    ("roundtrip_verified", "artifacts", "compared_sections"), {"file": "bracket.prt"}, verifier="roundtrip", effect="disk_and_memory", write=True)

# Session and environment: what a person settles before touching a model -- where Creo
# is pointed, which files are there, which config options are in force, and whether a
# model actually opened cleanly. Reads here deliberately do not require the target to be
# loaded; `file exists` that refused unloaded models would answer its own question.
# GLOB is narrower than the upstream wildcard field: listing accepts a bounded pattern,
# while every mutating command still names one exact model.
GLOB = text(pattern=r"^[A-Za-z0-9_*?][A-Za-z0-9_.*?-]{0,79}$")
add("creo pwd", "creo", "pwd", "Read Creo's current working directory", {}, ("dirname",), {}, target_keys=())
add("creo list-files", "creo", "list_files", "List files in Creo's working directory, optionally by a bounded pattern", {"filename": GLOB}, ("filelist",), {"filename": "*.prt"}, required=(), target_keys=(), list_key="filelist")
add("creo list-dirs", "creo", "list_dirs", "List subdirectories of Creo's working directory", {"dirname": GLOB}, ("dirlist",), {"dirname": "*"}, required=(), target_keys=(), list_key="dirlist")
add("creo get-config", "creo", "get_config", "Read the values in force for one named Creo config option", {"name": NAME}, ("values",), {"name": "pro_unit_length"}, target_keys=(), list_key="values")
add("server pwd", "server", "pwd", "Read the CREOSON service's own execution directory; not Creo's", {}, ("dirname",), {}, target_keys=())
add("file exists", "file", "exists", "Check whether a named model is in session memory", F, ("exists",), {"file": "bracket.prt"}, target_keys=())
add("file is-active", "file", "is_active", "Check whether a named model is the active one", F, ("active",), {"file": "bracket.prt"}, target_keys=())
add("file open-errors", "file", "open_errors", "Report whether Creo recorded errors opening a model", F, ("errors",), {"file": "bracket.prt"})

# Session writes. `creo cd` is the supported way to point Creo at the disposable
# workspace: the CLI has always refused to move it silently, and this makes the move an
# explicit, confirmed, read-back step instead. Directory paths stay workspace-contained.
add("creo cd", "creo", "cd", "Point Creo's working directory at an existing directory inside the workspace", {"dirname": PATH}, ("dirname",), {"dirname": "."}, target_keys=(), verifier="working_directory", effect="session", write=True)
add("creo mkdir", "creo", "mkdir", "Create one new directory inside the workspace", {"dirname": PATH}, ("dirname",), {"dirname": "exports"}, target_keys=(), verifier="directory_present", effect="disk", write=True)
add("creo rmdir", "creo", "rmdir", "Remove one existing directory inside the workspace", {"dirname": PATH}, (), {"dirname": "exports"}, target_keys=(), verifier="directory_absent", effect="disk", write=True, dangerous=True)
add("creo set-config", "creo", "set_config", "Set one named Creo config option and read the value back", {"name": NAME, "value": text(maximum=512), "ignore_errors": BOOL}, (), {"name": "regen_failure_handling", "value": "resolve_mode", "ignore_errors": False}, required=("name", "value"), target_keys=(), verifier="config_option", effect="session", write=True)
add("file refresh", "file", "refresh", "Refresh a model's window; changes display only", F, (), {"file": "bracket.prt"}, verifier="acknowledgement", effect="ui", write=True)
add("file repaint", "file", "repaint", "Repaint a model's window; changes display only", F, (), {"file": "bracket.prt"}, verifier="acknowledgement", effect="ui", write=True)

# Reading the model the way a person reads it on screen: how big it is, what surfaces
# and edges it has, which layers and notes carry intent, and what accuracy and unit
# system the numbers are expressed in. All observations -- nothing here changes state.
add("geometry bound-box", "geometry", "bound_box", "Read a model's bounding box in its own length units", F, ("xmin", "xmax", "ymin", "ymax", "zmin", "zmax"), {"file": "bracket.prt"}, verifier="observation")
add("geometry surfaces", "geometry", "get_surfaces", "Read surface identities with area and extents; not a tessellation or a BREP export", F, ("surflist",), {"file": "bracket.prt"}, list_key="surflist")
add("geometry edges", "geometry", "get_edges", "Read edge contours for explicitly named surface ids", F | {"surface_ids": {"type": "array", "items": text(pattern=r"^[0-9]{1,10}$"), "minItems": 1, "maxItems": 256}}, ("contourlist",), {"file": "bracket.prt", "surface_ids": ["1"]}, required=("file", "surface_ids"), list_key="contourlist")
add("file accuracy", "file", "get_accuracy", "Read modelling accuracy and whether it is relative or absolute", F, ("accuracy", "relative"), {"file": "bracket.prt"})
add("file unit-system", "file", "get_unit_system", "Read the model's principal unit system name", F, ("name",), {"file": "bracket.prt"})
add("file has-instances", "file", "has_instances", "Check whether a model owns a family table", F, ("exists",), {"file": "bracket.prt"})
add("file simp-reps", "file", "list_simp_reps", "List simplified representations defined on a model", F | {"rep": NAME}, ("reps",), {"file": "bracket.prt"}, required=("file",), list_key="reps")
add("layer list", "layer", "list", "Read layers with their display status", F | {"name": NAME}, ("layers",), {"file": "bracket.prt"}, required=("file",), list_key="layers")
add("layer exists", "layer", "exists", "Check whether a named layer is defined on a model", F | {"name": NAME}, ("exists",), {"file": "bracket.prt", "name": "DATUMS"}, required=("file",))
add("note list", "note", "list", "Read model notes, optionally expanding parameter references", F | {"name": NAME, "get_expanded": BOOL}, ("itemlist",), {"file": "bracket.prt"}, required=("file",), defaults={"select": False}, list_key="itemlist")
add("note get", "note", "get", "Read one named note's text and placement", F | {"name": NAME}, ("name", "value", "encoded", "url", "location"), {"file": "bracket.prt", "name": "NOTE_1"}, required=("file", "name"))
add("note exists", "note", "exists", "Check whether a named note is defined on a model", F | {"name": NAME}, ("exists",), {"file": "bracket.prt", "name": "NOTE_1"}, required=("file",))
add("parameter exists", "parameter", "exists", "Check whether a named parameter is defined on a model", F | {"name": NAME}, ("exists",), {"file": "bracket.prt", "name": "PART_NO"}, required=("file",))
add("feature params", "feature", "list_params", "Read parameters owned by features rather than by the model", F | {"name": NAME, "param": NAME}, ("paramlist",), {"file": "bracket.prt", "name": "HOLE_1"}, required=("file",), defaults={"encoded": False, "inc_unnamed": True}, list_key="paramlist")
add("feature param-exists", "feature", "param_exists", "Check whether a named feature carries a named parameter", F | {"name": NAME, "param": NAME}, ("exists",), {"file": "bracket.prt", "name": "HOLE_1", "param": "DEPTH"}, required=("file", "name"))
add("view list-exploded", "view", "list_exploded", "List exploded assembly states", F | {"name": NAME}, ("viewlist",), {"file": "device.asm"}, required=("file",), list_key="viewlist")

# Family tables: how a mechanical engineer actually ships variants of a part. Reads
# first, then the edits, each naming one exact instance -- no wildcard rows.
# `familytable.list_tree` publishes an `erase` flag that unloads models as a side effect
# of reading; it is pinned false here so a read can never quietly erase a session.
INSTANCE = text(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_-]{0,79}$")
COLUMN = text(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_.()\[\] -]{0,79}$")
FT = {"file": MODEL, "instance": INSTANCE}
add("familytable list", "familytable", "list", "List family-table instance names", F | {"instance": INSTANCE}, ("instances",), {"file": "bracket.prt"}, required=("file",), list_key="instances")
add("familytable exists", "familytable", "exists", "Check whether one named instance exists in a family table", FT, ("exists",), {"file": "bracket.prt", "instance": "bracket_s"}, required=("file", "instance"))
add("familytable header", "familytable", "get_header", "Read family-table column definitions", F, ("columns",), {"file": "bracket.prt"}, list_key="columns")
add("familytable row", "familytable", "get_row", "Read one family-table row by instance name", FT, ("instance", "columns"), {"file": "bracket.prt", "instance": "bracket_s"}, required=("file", "instance"))
add("familytable cell", "familytable", "get_cell", "Read one family-table cell with its declared data type", FT | {"colid": COLUMN}, ("instance", "colid", "value", "datatype", "coltype"), {"file": "bracket.prt", "instance": "bracket_s", "colid": "d1"}, required=("file", "instance", "colid"))
add("familytable parents", "familytable", "get_parents", "Read parent instances of a model in a nested family table", F, ("parents",), {"file": "bracket.prt"}, list_key="parents")
add("familytable tree", "familytable", "list_tree", "Read a nested family-table hierarchy without erasing anything", F, ("total", "children"), {"file": "bracket.prt"}, defaults={"erase": False})

add("familytable create-instance", "familytable", "create_inst", "Materialize one family-table row into a loaded model", FT, ("name",), {"file": "bracket.prt", "instance": "bracket_s"}, required=("file", "instance"), verifier="familytable_created", **W)
add("familytable add-instance", "familytable", "add_inst", "Add one named instance row; upstream creates the family table when absent", FT, (), {"file": "bracket.prt", "instance": "bracket_xl"}, required=("file", "instance"), verifier="familytable_present", **W)
add("familytable set-cell", "familytable", "set_cell", "Set one family-table cell against its expected declared data type", FT | {"colid": COLUMN, "value": PARAM_VALUE, "expected_datatype": text(enum=("STRING", "DOUBLE", "INTEGER", "BOOL"))}, (), {"file": "bracket.prt", "instance": "bracket_s", "colid": "d1", "value": 42, "expected_datatype": "DOUBLE"}, required=("file", "instance", "colid", "value", "expected_datatype"), local_keys=("expected_datatype",), verifier="familytable_cell", **W)
add("familytable replace", "familytable", "replace", "Swap one assembly component for another instance of the same family table", {"file": ASM, "cur_model": MODEL, "cur_inst": INSTANCE, "new_inst": INSTANCE, "path": {"type": "array", "items": text(pattern=r"^[0-9]{1,10}$"), "minItems": 1, "maxItems": 32}}, (), {"file": "device.asm", "cur_model": "bracket.prt", "cur_inst": "bracket_s", "new_inst": "bracket_l"}, required=("file", "cur_model", "new_inst"), target_keys=("file",), verifier="familytable_replaced", **W)
add("familytable delete-instance", "familytable", "delete_inst", "Remove one named instance row from a family table", FT, (), {"file": "bracket.prt", "instance": "bracket_s"}, required=("file", "instance"), verifier="familytable_absent", dangerous=True, **W)
add("familytable delete", "familytable", "delete", "Remove a model's entire family table and every variant it defines", F, (), {"file": "bracket.prt"}, verifier="familytable_table_absent", dangerous=True, **W)

# Drawings, read the way a person inspects a sheet: which sheet and model are current,
# how big the sheet is and at what scale, where each view sits and how large it is, and
# which symbols have been placed. Every target is named explicitly -- the upstream lets
# these default to the active drawing, which this adapter has never allowed.
SYMBOL_FILE = text(pattern=r"^[A-Za-z0-9_][A-Za-z0-9_.-]{0,120}$")
add("drawing current-sheet", "drawing", "get_cur_sheet", "Read which sheet of a drawing is current", D, ("sheet",), {"drawing": "bracket.drw"}, target_keys=("drawing",))
add("drawing current-model", "drawing", "get_cur_model", "Read a drawing's current model", D, ("file",), {"drawing": "bracket.drw"}, target_keys=("drawing",))
add("drawing sheet-size", "drawing", "get_sheet_size", "Read one sheet's size designation", D | {"sheet": SHEET}, ("size",), {"drawing": "bracket.drw", "sheet": 1}, target_keys=("drawing",))
add("drawing sheet-scale", "drawing", "get_sheet_scale", "Read one sheet's scale", D | {"sheet": SHEET, "model": MODEL}, ("scale",), {"drawing": "bracket.drw", "sheet": 1}, required=("drawing", "sheet"), target_keys=("drawing",))
add("drawing sheet-format", "drawing", "get_sheet_format", "Read the format applied to one sheet", D | {"sheet": SHEET}, ("file", "full_name", "common_name"), {"drawing": "bracket.drw", "sheet": 1}, target_keys=("drawing",))
add("drawing list-views", "drawing", "list_views", "List view names on a drawing", D | {"view": NAME}, ("views",), {"drawing": "bracket.drw"}, required=("drawing",), target_keys=("drawing",), list_key="views")
add("drawing view-location", "drawing", "get_view_loc", "Read one view's placement in drawing units", D | {"view": NAME}, ("x", "y", "z"), {"drawing": "bracket.drw", "view": "FRONT_MAIN"}, target_keys=("drawing",))
add("drawing view-scale", "drawing", "get_view_scale", "Read one view's scale", D | {"view": NAME}, ("scale",), {"drawing": "bracket.drw", "view": "FRONT_MAIN"}, target_keys=("drawing",))
add("drawing view-sheet", "drawing", "get_view_sheet", "Read which sheet carries one view", D | {"view": NAME}, ("sheet",), {"drawing": "bracket.drw", "view": "FRONT_MAIN"}, target_keys=("drawing",))
add("drawing view-bound-box", "drawing", "view_bound_box", "Read one view's bounding box in drawing units", D | {"view": NAME}, ("xmin", "xmax", "ymin", "ymax"), {"drawing": "bracket.drw", "view": "FRONT_MAIN"}, target_keys=("drawing",))
add("drawing list-symbols", "drawing", "list_symbols", "List placed symbol instances", D | {"symbol_file": SYMBOL_FILE, "sheet": SHEET}, ("symbols",), {"drawing": "bracket.drw"}, required=("drawing",), target_keys=("drawing",), list_key="symbols")
add("drawing symbol-loaded", "drawing", "is_symbol_def_loaded", "Check whether a symbol definition is loaded in a drawing", D | {"symbol_file": SYMBOL_FILE}, ("loaded",), {"drawing": "bracket.drw", "symbol_file": "note.sym"}, target_keys=("drawing",))

# Drawing edits. Where the upstream lets a target be omitted to mean "all of them"
# -- delete_models without a model, scale_view without a view -- this adapter requires
# the name, the same refusal of wildcard mutations applied everywhere else. View
# coordinates are declared in drawing units, never assumed.
DRAWING_UNITS = text(enum=("drawing_units",))
SYMBOL_ID = text(pattern=r"^[0-9]{1,10}$")
add("drawing select-sheet", "drawing", "select_sheet", "Make one sheet current", D | {"sheet": SHEET}, (), {"drawing": "bracket.drw", "sheet": 1}, target_keys=("drawing",), verifier="drawing_sheet_current", effect="ui", write=True)
add("drawing regenerate-sheet", "drawing", "regenerate_sheet", "Regenerate one sheet; does not certify its dimensions", D | {"sheet": SHEET}, (), {"drawing": "bracket.drw", "sheet": 1}, required=("drawing",), target_keys=("drawing",), verifier="acknowledgement", **W)
add("drawing scale-sheet", "drawing", "scale_sheet", "Set one sheet's scale and read it back", D | {"sheet": SHEET, "scale": POS, "model": MODEL}, (), {"drawing": "bracket.drw", "sheet": 1, "scale": 2}, required=("drawing", "sheet", "scale"), target_keys=("drawing",), verifier="drawing_sheet_scale", **W)
add("drawing set-sheet-format", "drawing", "set_sheet_format", "Apply a format file from the workspace to one sheet", D | {"sheet": SHEET, "file": SYMBOL_FILE, "dirname": PATH}, (), {"drawing": "bracket.drw", "sheet": 1, "file": "a4.drw", "dirname": "templates"}, required=("drawing", "sheet", "file"), target_keys=("drawing",), verifier="drawing_sheet_format", **W)
add("drawing delete-sheet", "drawing", "delete_sheet", "Delete one sheet and everything placed on it", D | {"sheet": SHEET}, (), {"drawing": "bracket.drw", "sheet": 2}, target_keys=("drawing",), verifier="drawing_sheet_count", dangerous=True, **W)
add("drawing set-current-model", "drawing", "set_cur_model", "Make one contained model current in a drawing", D | {"model": MODEL}, (), {"drawing": "bracket.drw", "model": "bracket.prt"}, target_keys=("drawing", "model"), verifier="drawing_model_current", **W)
add("drawing delete-models", "drawing", "delete_models", "Remove one named model from a drawing; the name is required, never all models", D | {"model": MODEL, "delete_views": BOOL}, (), {"drawing": "bracket.drw", "model": "bracket.prt", "delete_views": True}, required=("drawing", "model"), target_keys=("drawing",), verifier="drawing_model_absent", dangerous=True, **W)
add("drawing rename-view", "drawing", "rename_view", "Rename one view and confirm both names moved", D | {"view": NAME, "new_view": NAME}, (), {"drawing": "bracket.drw", "view": "FRONT_MAIN", "new_view": "FRONT_A"}, target_keys=("drawing",), verifier="drawing_view_renamed", **W)
add("drawing move-view", "drawing", "set_view_loc", "Move one view to an explicit position in drawing units", D | {"view": NAME, "point": POINT, "coordinate_units": DRAWING_UNITS}, (), {"drawing": "bracket.drw", "view": "FRONT_MAIN", "point": {"x": 120, "y": 90}, "coordinate_units": "drawing_units"}, target_keys=("drawing",), local_keys=("coordinate_units",), verifier="drawing_view_moved", **W)
add("drawing scale-view", "drawing", "scale_view", "Set one named view's scale; the name is required, never every view at once", D | {"view": NAME, "scale": POS}, ("success_views", "failed_views"), {"drawing": "bracket.drw", "view": "FRONT_MAIN", "scale": 2}, required=("drawing", "view", "scale"), target_keys=("drawing",), verifier="drawing_view_scaled", **W)
add("drawing delete-view", "drawing", "delete_view", "Delete one named view; child views are kept unless asked for", D | {"view": NAME, "sheet": SHEET, "del_children": BOOL}, (), {"drawing": "bracket.drw", "view": "RIGHT_PROJECTED"}, required=("drawing", "view"), target_keys=("drawing",), defaults={"del_children": False}, verifier="drawing_view_absent", dangerous=True, **W)
add("drawing load-symbol", "drawing", "load_symbol_def", "Load a symbol definition from the workspace into a drawing", D | {"symbol_file": SYMBOL_FILE, "symbol_dir": PATH}, ("id", "name"), {"drawing": "bracket.drw", "symbol_file": "note.sym", "symbol_dir": "templates"}, required=("drawing", "symbol_file"), target_keys=("drawing",), verifier="drawing_symbol_loaded", **W)
add("drawing place-symbol", "drawing", "create_symbol", "Place one loaded symbol at an explicit point in drawing units", D | {"symbol_file": SYMBOL_FILE, "point": POINT, "sheet": SHEET, "coordinate_units": DRAWING_UNITS, "replace_values": {"type": "object", "additionalProperties": text(maximum=512), "maxProperties": 32}}, (), {"drawing": "bracket.drw", "symbol_file": "note.sym", "point": {"x": 50, "y": 20}, "sheet": 1, "coordinate_units": "drawing_units"}, required=("drawing", "symbol_file", "point", "coordinate_units"), target_keys=("drawing",), local_keys=("coordinate_units",), verifier="drawing_symbol_placed", **W)
add("drawing delete-symbol-definition", "drawing", "delete_symbol_def", "Unload a symbol definition and every instance of it", D | {"symbol_file": SYMBOL_FILE}, (), {"drawing": "bracket.drw", "symbol_file": "note.sym"}, target_keys=("drawing",), verifier="drawing_symbol_definition_absent", dangerous=True, **W)
add("drawing delete-symbol-instance", "drawing", "delete_symbol_inst", "Delete one placed symbol instance by id", D | {"symbol_id": SYMBOL_ID}, (), {"drawing": "bracket.drw", "symbol_id": "1"}, target_keys=("drawing",), verifier="drawing_symbol_instance_absent", dangerous=True, **W)

# Editing the model. Two upstream defaults are refused outright here:
# `file.erase_not_displayed` takes no target at all and erases whatever is not on
# screen, and the unit setters carry a `convert` flag that decides whether 40 mm
# becomes 40 in or 1.575 in. That flag is required with no default -- reinterpreting
# every dimension in a model is not something to inherit from a wire default.
MATERIAL_GLOB = text(pattern=r"^[A-Za-z0-9_*?][A-Za-z0-9_.*?-]{0,79}$")
RELATIONS = {"type": "array", "items": text(maximum=512), "maxItems": 2000}
CONVERT = {"type": "boolean"}
add("file mass-units-only", "file", "get_mass_units", "Read only the mass units, without the length units file units also returns", F, ("units",), {"file": "bracket.prt"})
add("file materials-wildcard", "file", "list_materials_wildcard", "List materials matching a bounded pattern across loaded parts", {"file": PART, "material": MATERIAL_GLOB, "include_non_matching_parts": BOOL}, ("materials",), {"file": "bracket.prt", "material": "*"}, required=("file",), list_key="materials")
add("file current-material-wildcard", "file", "get_cur_material_wildcard", "Read assigned materials across loaded parts", {"file": PART, "include_non_matching_parts": BOOL}, ("materials",), {"file": "bracket.prt"}, required=("file",), list_key="materials")
add("file postregen-relations", "file", "postregen_relations_get", "Read post-regeneration relations without evaluating them", F, ("relations",), {"file": "bracket.prt"}, list_key="relations")

add("file rename", "file", "rename", "Rename a model, choosing explicitly whether the disk file moves too", F | {"new_name": MODEL, "onlysession": BOOL}, ("file",), {"file": "bracket.prt", "new_name": "bracket_v2.prt", "onlysession": True}, required=("file", "new_name", "onlysession"), verifier="renamed", effect="disk_and_memory", write=True)
add("file erase", "file", "erase", "Remove one named model from session memory; unsaved changes in it are lost", F | {"erase_children": BOOL}, (), {"file": "bracket.prt", "erase_children": False}, required=("file", "erase_children"), verifier="erased", dangerous=True, **W)
add("file set-length-units", "file", "set_length_units", "Set length units, stating whether existing geometry is converted or reinterpreted", F | {"units": LENGTH, "convert": CONVERT}, (), {"file": "bracket.prt", "units": "mm", "convert": True}, required=("file", "units", "convert"), verifier="length_units", **W)
add("file set-mass-units", "file", "set_mass_units", "Set mass units, stating whether existing values are converted or reinterpreted", F | {"units": text(enum=("g", "kg", "lb", "oz", "tonne")), "convert": CONVERT}, (), {"file": "bracket.prt", "units": "kg", "convert": True}, required=("file", "units", "convert"), verifier="mass_units", **W)
add("file set-unit-system", "file", "set_unit_system", "Apply a named unit system, stating whether existing values are converted", F | {"name": NAME, "convert": CONVERT}, (), {"file": "bracket.prt", "name": "mmNs", "convert": True}, required=("file", "name", "convert"), verifier="unit_system", **W)
add("file create-unit-system", "file", "create_unit_system", "Define a new named unit system on a model", F | {"name": NAME, "unit_length": LENGTH, "unit_mass": text(enum=("g", "kg", "lb", "oz", "tonne")), "unit_time": text(enum=("sec", "min", "hr")), "unit_temp": text(enum=("C", "F", "K", "R"))}, (), {"file": "bracket.prt", "name": "custom_mmks", "unit_length": "mm", "unit_mass": "kg", "unit_time": "sec", "unit_temp": "C"}, required=("file", "name", "unit_length", "unit_mass", "unit_time", "unit_temp"), verifier="acknowledgement", **W)
add("file load-material", "file", "load_material_file", "Load a material definition from the workspace into a part", {"file": PART, "material": NAME, "dirname": PATH}, ("files",), {"file": "bracket.prt", "material": "TITANIUM", "dirname": "."}, required=("file", "material"), verifier="material_present", **W)
add("file delete-material", "file", "delete_material", "Remove one material definition from a part", {"file": PART, "material": NAME}, ("files",), {"file": "bracket.prt", "material": "STEEL"}, required=("file", "material"), verifier="material_absent", dangerous=True, **W)
add("file set-relations", "file", "relations_set", "Replace a model's relations wholesale; the CLI does not evaluate the text", F | {"relations": RELATIONS}, (), {"file": "bracket.prt", "relations": ["d1 = 45"]}, required=("file", "relations"), verifier="relations", dangerous=True, **W)
add("file set-postregen-relations", "file", "postregen_relations_set", "Replace post-regeneration relations wholesale", F | {"relations": RELATIONS}, (), {"file": "bracket.prt", "relations": ["d2 = d1 / 8"]}, required=("file", "relations"), verifier="postregen_relations", dangerous=True, **W)

add("parameter copy", "parameter", "copy", "Copy one parameter to another name or model", F | {"name": NAME, "to_name": NAME, "to_file": MODEL, "designate": BOOL}, (), {"file": "bracket.prt", "name": "PART_NO", "to_name": "PART_NO_REV"}, required=("file", "name", "to_name"), target_keys=("file",), verifier="parameter_copied", **W)
add("parameter delete", "parameter", "delete", "Delete one named parameter", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "PART_NO"}, required=("file", "name"), verifier="parameter_absent", dangerous=True, **W)
add("parameter set-designated", "parameter", "set_designated", "Set whether one parameter is designated for the family table", F | {"name": NAME, "designate": BOOL}, (), {"file": "bracket.prt", "name": "PART_NO", "designate": True}, required=("file", "name", "designate"), verifier="parameter_designated", **W)

add("dimension list-basic", "dimension", "list", "Read dimension names and values without the drawing detail list_detail returns", F | {"name": NAME, "dim_type": text(enum=("linear", "radial", "diameter", "angular"))}, ("dimlist",), {"file": "bracket.prt"}, required=("file",), defaults={"encoded": False, "select": False}, list_key="dimlist")
add("dimension copy", "dimension", "copy", "Copy one dimension to another name or model", F | {"name": NAME, "to_name": NAME, "to_file": MODEL}, (), {"file": "bracket.prt", "name": "d1", "to_name": "d1_copy"}, required=("file", "name", "to_name"), target_keys=("file",), verifier="dimension_copied", **W)
add("dimension set-text", "dimension", "set_text", "Set one dimension's display text without changing its value", F | {"name": NAME, "text": text(maximum=512)}, (), {"file": "bracket.prt", "name": "d1", "text": "45 REF"}, required=("file", "name", "text"), defaults={"encoded": False}, verifier="dimension_text", **W)
add("dimension show", "dimension", "show", "Show or hide one dimension, optionally through an explicit assembly path", F | {"name": NAME, "assembly": ASM, "path": {"type": "array", "items": text(pattern=r"^[0-9]{1,10}$"), "minItems": 1, "maxItems": 32}, "show": BOOL}, (), {"file": "bracket.prt", "name": "d1", "show": True}, required=("file", "name", "show"), verifier="acknowledgement", effect="ui", write=True)

add("feature delete", "feature", "delete", "Delete exactly one named feature; never a status or type sweep", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "HOLE_1"}, required=("file", "name"), defaults={"clip": False}, verifier="feature_absent", dangerous=True, **W)
add("feature set-param", "feature", "set_param", "Set one typed parameter on one named feature", F | {"name": NAME, "param": NAME, "type": text(enum=("STRING", "DOUBLE", "INTEGER", "BOOL")), "value": PARAM_VALUE, "designate": BOOL}, (), {"file": "bracket.prt", "name": "HOLE_1", "param": "DEPTH", "type": "STRING", "value": "THRU"}, required=("file", "name", "param", "type", "value"), defaults={"encoded": False, "no_create": False}, verifier="feature_param", **W)
add("feature delete-param", "feature", "delete_param", "Delete one named parameter from one named feature", F | {"name": NAME, "param": NAME}, (), {"file": "bracket.prt", "name": "HOLE_1", "param": "DEPTH"}, required=("file", "name", "param"), verifier="feature_param_absent", dangerous=True, **W)
add("feature group-features", "feature", "list_group_features", "List the features inside one named group", F | {"group_name": NAME, "type": NAME}, ("featlist",), {"file": "bracket.prt", "group_name": "GROUP_1"}, required=("file", "group_name"), list_key="featlist")
add("feature pattern-features", "feature", "list_pattern_features", "List the features produced by one named pattern", F | {"pattern_name": NAME, "type": NAME}, ("featlist",), {"file": "bracket.prt", "pattern_name": "PATTERN_1"}, required=("file", "pattern_name"), list_key="featlist")

add("note set", "note", "set", "Create or update one named note's text", F | {"name": NAME, "value": text(maximum=4000), "location": POINT}, (), {"file": "bracket.prt", "name": "NOTE_1", "value": "BREAK SHARP EDGES"}, required=("file", "name", "value"), defaults={"encoded": False}, verifier="note_present", **W)
add("note copy", "note", "copy", "Copy one note to another name or model", F | {"name": NAME, "to_name": NAME, "to_file": MODEL}, (), {"file": "bracket.prt", "name": "NOTE_1", "to_name": "NOTE_2"}, required=("file", "name", "to_name"), target_keys=("file",), verifier="note_copied", **W)
add("note delete", "note", "delete", "Delete one named note", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "NOTE_1"}, required=("file", "name"), verifier="note_absent", dangerous=True, **W)

add("layer show", "layer", "show", "Show or hide one named layer", F | {"name": NAME, "show": BOOL}, (), {"file": "bracket.prt", "name": "DATUMS", "show": True}, required=("file", "name", "show"), verifier="layer_status", effect="ui", write=True)
add("layer delete", "layer", "delete", "Delete one named layer", F | {"name": NAME}, (), {"file": "bracket.prt", "name": "DATUMS"}, required=("file", "name"), verifier="layer_absent", dangerous=True, **W)

BY_PATH = {op.path: op for op in OPS}
